### ISSUE TITLE
Question about scaling and feature selection

### ISSUE THREAD

**Issue by jessicaliu09** [UrbsLab/STREAMLINE#6]
Hi,  

Because our data is zero-inflated, we want to use MaxAbsScaler. So when we turn off the scaling, it has error during the feature selection step. See errors below. 

So we want to turn off scaling and keep feature selection, how should we set up the parameters? Thanks. 

INFO: Applying collective feature selection...
Traceback (most recent call last):
  File "/N/slate/shiwliu/STREAMLINE/0.1.STREAMLINE-Notebook.py", line 492, in <module>
    f_sel.run(run_parallel=False)
  File "/N/slate/shiwliu/STREAMLINE/streamline/runners/feature_runner.py", line 324, in run
    job_obj.run()
  File "/N/slate/shiwliu/STREAMLINE/streamline/featurefns/selection.py", line 79, in run
    self.select_features(selected_feature_lists,
  File "/N/slate/shiwliu/STREAMLINE/streamline/featurefns/selection.py", line 254, in select_features
    if len(union_list) > max_features_to_keep:  # Apply further filtering if more than max features remains
TypeError: '>' not supported between instances of 'int' and 'NoneType'

**Comment by raptor419** [comment]
Thanks for reporting this. This issue appears to come from the older feature-selection workflow receiving an unexpected `None` value. Depending on the run settings/output state, that could have been either `max_features_to_keep = None` or a missing/empty feature-selection union list, which then led to the comparison `len(union_list) > max_features_to_keep` failing.

So this was not really a MaxAbsScaler-specific issue. Scaling and feature selection were separate steps, but the feature-selection inputs/defaults needed to be defined correctly.

For the older notebook/version, the workaround is to keep feature selection on but make sure the feature-selection inputs are defined: set `max_features_to_keep` to an integer value and confirm that the upstream feature-importance/selection step produced a valid feature list.

We are releasing STREAMLINE v3, where the pipeline has a much cleaner registry-based extension structure. In v3, users can add their own scalers through the Phase 2 scaler registry, so a `MaxAbsScaler` option can be added cleanly without modifying the rest of the pipeline. The same registry pattern is also used across other phases, making it easier to add or swap methods in a maintainable way.

For zero-inflated data, `MaxAbsScaler` is still a reasonable scaling choice, and feature selection can be kept on as long as the feature-selection cap/top-feature setting is defined and a valid upstream feature list is produced.

Closing this as resolved/obsolete with the v3 refactor.
